### ISSUE TITLE
Webrtc build issue

### ISSUE THREAD

**Issue by samofoz** [CoSMoSoftware/CSM-IE-WebRTC-plugin#1]
Hi there, I can't seem to build webrtc build 65. I get the following error upon doing a gn gen. Please help.

C:\webrtc\webrtc-checkout\src>gn gen out/Default
ERROR at //BUILD.gn:19:3: Can't load input file.
  import("//third_party/protobuf/proto_library.gni")
  ^------------------------------------------------
Unable to load:
  C:/webrtc/webrtc-checkout/src/third_party/protobuf/proto_library.gni
I also checked in the secondary tree for:
  C:/webrtc/webrtc-checkout/src/build/secondary/third_party/protobuf/proto_library.gni

**Comment by agouaillard-cosmo** [comment]
This project is not about building webrtc. webrtc discussions happen on the discuss-webrtc mailing list.
