### ISSUE TITLE
plugin compile help

### ISSUE THREAD

**Issue by brawman** [CoSMoSoftware/CSM-IE-WebRTC-plugin#3]
hello,

thank you for your contribution of webrtc.

i want to use this plugin.

so i was compile libwebrtc and i have plan to compile the plugin with libwebrtc.

but i don't know how to compile this plugin.

could you help me how to compile the plugin with libwebrtc??

just short tip is biggest help for me.

i use msvs 2019 and got webrtc.lib

thanks.

**Comment by agouaillard-cosmo** [comment]
Hi brawman,

This plugin code is not supported anymore. We leave the code online for people to inspire themselves from if they so desire but will not answer any question about it.

best luck.
